### ISSUE TITLE
Idk what happend

### ISSUE THREAD

**Issue by trshyy** [PryosCode/CustomDiscordRPC#2]
![Discord RPC](https://user-images.githubusercontent.com/75910981/105871174-54416780-5ff9-11eb-855a-5672f6a5157c.png)

**Comment by PryosCode** [comment]
This error occurs when the program can't parse the config file. Could you attach your config to this issue?

**Comment by trshyy** [comment]
You're from Austria right? So can we write German? xd My english isn't that good

**Comment by trshyy** [comment]
In which file path can I find the config?

**Comment by PryosCode** [comment]
Die Datei findest du unter `%appdata%\PryosCode\CustomDiscordRPC\config.json`

**Comment by trshyy** [comment]
![Discord rpc2](https://user-images.githubusercontent.com/75910981/105876866-a8e7e100-5fff-11eb-8f5c-7ecdfd9ba36c.png)
Fehlt dort nicht nh Zeile?

**Comment by PryosCode** [comment]
State fehlt.
Wenn State lehr sein soll, dann kannst du es einfach so schreiben `"State": "",`

**Comment by PryosCode** [comment]
Und der `,` nach Details.

**Comment by trshyy** [comment]
Jo, danke habs geändert

**Comment by trshyy** [comment]
Funktioniert wieder.
